kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pto-pdfgen
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-pdfgen/pto-pdfgen:{{version}}
  port: 8080
  liveness:
    path: /is_alive
  readiness:
    path: /is_alive
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    min: 1
    max: 4
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
