apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pto-pdfgen
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://pto-pdfgen.intern.dev.nav.no
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_alive
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 250m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: veilarbvedtaksstotte
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
