kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pto-pdfgen
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 4
  resources:
    limits:
      cpu: {{ resources_limits_cpu }}
      memory: {{ resources_limits_memory }}
    requests:
      cpu: {{ resources_requests_cpu }}
      memory: {{ resources_requests_memory }}
