apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pto-pdfgen
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://pto-pdfgen.intern.dev.nav.no
  liveness:
    path: /is_alive
  readiness:
    path: /is_alive
  prometheus:
    enabled: true
    path: /prometheus
  replicas:
    min: 1
    max: 4
  resources:
    limits:
      cpu: {{ resources_limits_cpu }}
      memory: {{ resources_limits_memory }}
    requests:
      cpu: {{ resources_requests_cpu }}
      memory: {{ resources_requests_memory }}
  accessPolicy:
    inbound:
      rules:
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: dev-fss
