name: Deploy to dev
on:
  workflow_dispatch:
env:
  IMAGE_TAG: ${{ github.sha }}
  PRINT_PAYLOAD: true
jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Build and push Docker image
        uses: nais/docker-build-push@078e460885ed0424b60d45ce9220b4be1748be9d # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: obo

  deploy-dev:
    name: Deploy application to dev
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Deploy application
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/application-config-dev.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}
