name: Deploy to dev
on:
  workflow_dispatch:
env:
  IMAGE_TAG: ${{ github.sha }}
  PRINT_PAYLOAD: true
jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v6

      - name: Build and push Docker image
        uses: nais/docker-build-push@0e73849f69ff260ee27597553c0a7848ca4e9795 # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: obo

  deploy-dev:
    name: Deploy application to dev
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v6

      - name: Deploy application
        uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/application-config-dev.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}
