name: Deploy to dev
on:
  workflow_dispatch:
env:
  IMAGE_TAG: ${{ github.sha }}
  PRINT_PAYLOAD: true
jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Build and push Docker image
        uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: obo

  deploy-dev:
    name: Deploy application to dev
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Deploy application
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/application-config-dev.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}
