name: Test, build, push and deploy
on: push
env:
  IMAGE_TAG: ${{ github.sha }}
  PRINT_PAYLOAD: true
permissions:
  packages: write
  contents: write
jobs:
  build-and-push:
    name: Build and push
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pto
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy application to dev
    if: github.ref == 'refs/heads/dev'
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/nais.yaml
          VARS: nais/vars-dev.yml
          VAR: image=${{ needs.build-and-push.outputs.image }}

  deploy-prod:
    name: Deploy application to prod
    if: github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: nais/nais.yaml
          VARS: nais/vars-prod.yml
          VAR: image=${{ needs.build-and-push.outputs.image }}

  release-prod:
    name: Create prod release
    needs: deploy-prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release to prod
          target_commitish: main
          tag_name: release/prod@${{ env.IMAGE_TAG }}
          prerelease: false

